# Site settings
title: csertant
email: csertant@edu.bme.hu
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: I'm avoiding Twitter
github_username:  csertant
linkedin_name: Tamas Csertan
linkedin_profile: https://www.linkedin.com/in/tam%C3%A1s-csert%C3%A1n-76102a175

# Build settings
markdown: kramdown
